CLB: Filter out foil EA cards
taw/magic-search-engine pull request #299
Opened 2024-01-09 13:14 UTC by kodawah

I've gotten a report that we include too many cards in the collector booster for CLB

https://docs.google.com/spreadsheets/d/1vXSBHt0cJAFhkU404hfOlXTSANaLT1Z3Becjixf6aXs/edit#gid=1240952972

the cards in yellow appear in the sample boosters not the collector boosters, and the wotc article confirms that
> 1 Non-foil extended-art rare or mythic rare from the Commander Legends: Battle for Baldur's Gate set
> 1 Non-foil extended-art rare or mythic rare from Commander Legends: Battle for Baldur's Gate Commander set

however
1. https://mtg.wtf/card?q=e%3Aclb+number%3A553-606+-is%3Afoil returns an empty set
2. i don't know where the non-ea mythic foils (like Durnan of the Yawning Portal) come from

@taw can you advise?
cc @axxroytovu

2024-01-10 01:30 UTC, the-muppet commented
the come from the commander decks

2024-01-29 11:32 UTC, taw commented
@kodawah @axxroytovu Does anything need to be done about this issue?

2024-01-29 12:54 UTC, kodawah commented
@taw the second query should return some cards, but it's empty

2024-01-29 13:19 UTC, taw commented
Is this an issue with mtgjson foiling data? Foil data comes from mtgjson directly (other than small number of bugfixes in indexer). So it's probably best to report this upstream.

2024-01-29 13:45 UTC, the-muppet commented
assuming we're talking about the same cards - using Durnan as the example still; they are correct within mtgjson

2024-01-29 15:23 UTC, kodawah commented
> I dislike e:clb number:607-645 -is:foil from a reliability standpoint, since relying on the foiling for cards that may or may not have different foiling is risky. I'd prefer e:clb number:607-645 -alt:(e:clb number:646-657), since it excludes the same cards and is both clearer and less prone to future database changes.

that wouldn't match what the card distribution model describes afaict

2024-01-30 18:45 UTC, axxroytovu commented
https://mtg.wtf/card?q=e%3Aclb+number%3A607-645+-alt%3A%28e%3Aclb+number%3A646-657%29+%2B%2B

Can you explain your comment further? Checking the above it does correctly reduce the card count from 40 to 28, excluding the specific 12 cards you highlighted in the spreadsheet.

2024-01-30 18:47 UTC, axxroytovu commented
Also `e:clb number:607-645 -is:foil` incorrectly removes Harper Recruiter and Stand Alone, which do correctly appear in collector boosters.

2024-01-30 21:43 UTC, axxroytovu commented
I think that's wrong, since those cards definitely exist in foil. https://www.tcgplayer.com/product/273435?Printing=Foil&page=1&irclickid=UfPwmNT-8xyPWCty-6Ww21zPUkHz9:3JLwaVQA0&sharedid=&irpid=4931599&irgwc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Scryfall&Language=English

2024-01-30 22:46 UTC, kodawah commented
> I think your mtgban query is wrong, since those cards definitely exist in foil. https://www.tcgplayer.com/product/273435?Printing=Foil&page=1&irclickid=UfPwmNT-8xyPWCty-6Ww21zPUkHz9:3JLwaVQA0&sharedid=&irpid=4931599&irgwc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Scryfall&Language=English

they exist in foil, they are just no found in CBB, but rather in sample packs

2024-01-30 23:30 UTC, the-muppet commented
Archivist is in collector boosters fwiw

2024-01-31 01:13 UTC, kodawah commented
> they exist in foil, they are just no found in CBB, but rather in sample packs
> Archivist is in collector boosters fwiw

for clarity:
* the NON FOIL VERSION appears in CBB *only*
* the FOIL VERSION appears in Sample Packs
* BOTH VERSIONS exists
* mtg.wtf search query returns empty when the NON FOIL version is selected
* this prevents the correct version to be added to the cbb sheet

hope it's clear now

2024-01-31 01:24 UTC, axxroytovu commented
Ok, so:
- The slot you're trying to edit, `extended_rare_mythic`, is a nonfoil slot, so it already doesn't include the foil versions.
- Searching `-is:foil` will remove any card that has a foil version. So the query is correctly returning no cards because the foil versions do exist.
- If you leave the slot the way it was, `filter: "e:clb number:553-606"`, it will have the correct cards for that slot in nonfoil.

2024-01-31 01:47 UTC, the-muppet commented
> > they exist in foil, they are just no found in CBB, but rather in sample packs
> > Archivist is in collector boosters fwiw
> 
> for clarity:
> 
> * the NON FOIL VERSION appears in CBB _only_
> * the FOIL VERSION appears in Sample Packs
> * BOTH VERSIONS exist
> * mtg.wtf search query returns empty when the NON FOIL version is selected
> * the empty query prevents the correct version from being added to the cbb sheet
> 
> hope it's clear now

Hi. 
Me again...
Your first bullet is incorrect.

2024-01-31 10:39 UTC, kodawah commented
> > > they exist in foil, they are just no found in CBB, but rather in sample packs
> > > Archivist is in collector boosters fwiw
> > 
> > 
> > for clarity:
> > 
> > * the NON FOIL VERSION appears in CBB _only_
> > * the FOIL VERSION appears in Sample Packs
> > * BOTH VERSIONS exist
> > * mtg.wtf search query returns empty when the NON FOIL version is selected
> > * the empty query prevents the correct version from being added to the cbb sheet
> > 
> > hope it's clear now
> 
> Hi. Me again... Your first bullet is incorrect.

wait what? is the article linked wrong then?

    1 Non-foil extended-art rare or mythic rare from the Commander Legends: Battle for Baldur's Gate set
    1 Non-foil extended-art rare or mythic rare from Commander Legends: Battle for Baldur's Gate Commander set

@axxroytovu I think I'm lost, any chance you could take over the patch?

2024-01-31 11:36 UTC, the-muppet commented
I dont know anything about any articles... But If it says that non foil EA archivist is **only** found in collector booster boxes.. then yes, the article is wrong. 

not trying to be a buzzkill :/

Source: Myself. Having opened somewhere north of a thousand of them

2024-01-31 14:16 UTC, kodawah commented
this is the article im referencing btw https://magic.wizards.com/en/news/feature/collecting-commander-legends-battle-for-baldurs-gate

2024-01-31 14:26 UTC, the-muppet commented
I redact all statements and claims made on this thread and bid you all adieu.

2024-02-11 01:15 UTC, axxroytovu requested changes
Added requested changes inline

2024-02-11 01:15 UTC, axxroytovu commented on data/boosters/clb-collector.yaml
> +    filter: "e:clb number:553-606 -is:foil"
Line is correct as is, leave this as `filter: "e:clb number:553-606"`

2024-02-11 01:15 UTC, axxroytovu commented on data/boosters/clb-collector.yaml
> +    filter: "e:clb number:607-645 -is:foil"
Change this line to: 
`filter: "e:clb number:607-645 -alt:(e:clb number:646-657)"`

2024-02-11 13:00 UTC, kodawah commented
updated

2024-02-11 17:52 UTC, axxroytovu approved these changes

2024-02-11 23:21 UTC, merged